package com.app.cattlemanagement.utils;

public class Constant {
    public static final String FARMER_COLLECTION = "Farmer";
    public static final String CATTLE_COLLECTION = "Cattle";
    public static final String GOAT_COLLECTION = "Goat";
    public static final String SHEEP_COLLECTION = "Sheep";
    public static final String FARM_OWNER = "Farmer";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String MALE = "Male";
    public static final String ANIMAL = "animal";
    public static final String FEMALE = "Female";
    public static final String BUYER = "BUYER";
    public static final String IMAGE = "image/*";
    public static final String CATTLE_IMAGE = "cattle";
    public static final String GET_ROLE = "GET_ROLE";
    public static final String USERNAME = "userName";
    public static final String EMAIl = "email";
    public static final String PASSWORD = "password";
    public static final String FRAGMENT_TAG = "MATERIAL_DATE_PICKER";
    public static final String NAME = "name";
    public static final String FIRST_VACCINE_NAME = "firstVaccineName";
    public static final String FIRST_VACCINE_DATE = "firstVaccineDate";
    public static final String SECOND_VACCINE_NAME = "secondVaccineName";
    public static final String SECOND_VACCINE_DATE = "secondVaccineDate";
    public static final String THIRD_VACCINE_NAME = "thirdVaccineName";
    public static final String THIRD_VACCINE_DATE = "thirdVaccineDate";
    public static final String FOURTH_VACCINE_NAME = "fourthVaccineName";
    public static final String FOURTH_VACCINE_DATE = "fourthVaccineDate";

    public static final String R_FIRST_VACCINE_NAME = "rfirstVaccineName";
    public static final String R_FIRST_VACCINE_DATE = "rfirstVaccineDate";
    public static final String R_SECOND_VACCINE_NAME = "rsecondVaccineName";
    public static final String R_SECOND__VACCINE_DATE = "rsecondVaccineDate";
    public static final String R_THIRD_VACCINE_NAME = "rthirdVaccineName";
    public static final String R_THIRD_VACCINE_DATE = "rthirdVaccineDate";
    public static final String CHILD_NO = "childNo";
    public static final String IS_FULLY_VACCINATED = "isFullyVaccinated";
    public static final String VACCINE_COMPLETED = "vaccineComplete";
    public static final String REMAINING_VACCCINE = "remainingVaccine";

    public static final String TAG = "tagNo";
    public static final String GENDER = "gender";
    public static final String IS_PREGNANT = "isPregnant";
    public static final String PREGNANT_MONTH = "pregnantMonth";
    public static final String OBTAINED_SOURCE = "obtainedSource";
    public static final String BREED = "breed";
    public static final String DOB = "dateOfBirth";
    public static final String DOB_FARM = "dateOfFarm";
    public static final String WEIGHT = "weight";
    public static final String MOTHER_TAG = "motherTagNo";
    public static final String FATHER_TAG = "fatherTagNo";
    public static final String ANIMAL_DESC = "desc";
    public static final String VACCINE_DETAIL = "vaccineDesc";
    public static final String IMAGE_URI = "imageUri";
    public static final String GOAT = "goat";
    public static final String SHEEP = "sheep";
    public static final String COWBULL = "cowBull";
    public static final String REF_DOC = "refDoc";
    public static final String VaccinatedYes = "Vaccinated-Yes";
    public static final String VaccinatedNo = "Vaccinated-No";
    public static final String HEALTHY = "Healthy";
    public static final String DISEASED = "Diseased";
    public static final String HEALTH_STATUS = "healthStatus";
    public static final String ZERO = "0";
    public static final String Grass_Feed = "Grass_Feed";
    public static final String Corn_Feed = "Corn_Feed";
    public static final String Barley_Feed = "Barley_Feed";
    public static final String Hay = "Hay";
    public static final String Straw = "Straw";
    public static final String Chaffhaye = "Chaffhaye";
    public static final String Grain = "Grain";
    public static final String Silage = "Silage";
    public static final String Goat_Feed = "Goat_Feed";
    public static final String Sheep_Feed = "Sheep_Feed";
    public static final String Cattle_Feed = "Cattle Feed";
    public static final String CONSUMED = "consumed";
    public static final String feedType = "feedType";
    public static final String REMAINING = "remaining";
    public static final String TOTAL_QUANTITY = "totalQuantity";
    public static final String CATTLE_FEED_GRASS = Cattle_Feed + "/" + Grass_Feed;
    public static final String GOAT_FEED_GRASS = Cattle_Feed + "/" + Grass_Feed;
    public static final String CATTLE_FEED_CORN = Cattle_Feed + "/" + Corn_Feed;
    public static final String GOAT_FEED_Chaffhaye = Goat_Feed + "/" +Chaffhaye  ;
    public static final String CATTLE_FEED_Hay = Goat_Feed + "/" + Hay;
    public static final String GOAT_FEED_Straw = Goat_Feed + "/" + Straw;
    public static final String SHEEP_FEED_Grain = Goat_Feed + "/" + Grain;
    public static final String INCREMENT = "INCREMENT";
    public static final String DECREMENT = "DECREMENT";

            ;

}
